# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcSens <- function(h, m) {
    .Call(`_CAMO_calcSens`, h, m)
}

calcSpec <- function(h, m) {
    .Call(`_CAMO_calcSpec`, h, m)
}

calcPrec <- function(h, m) {
    .Call(`_CAMO_calcPrec`, h, m)
}

calcESens <- function(h, m) {
    .Call(`_CAMO_calcESens`, h, m)
}

calcESpec <- function(h, m) {
    .Call(`_CAMO_calcESpec`, h, m)
}

calcEPrec <- function(h, m) {
    .Call(`_CAMO_calcEPrec`, h, m)
}

MCMC <- function(Z, iteration, gamma) {
    .Call(`_CAMO_MCMC`, Z, iteration, gamma)
}

